name: continuous-integration/jenkins

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        continue-on-error: true
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set jenkins status to pending
        continue-on-error: true
        run: |
          curl -u ${GITHUB_ACTOR}:${{ github.token }} "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA}" -H "Content-Type: application/json" -X POST -d "{\"state\": \"pending\",\"context\": \"Jenkins/test-branch\", \"description\": \"needs to run k8s or k8s is not finished yet\", \"target_url\": \"http://jenkins-development.nextinsurance.io/view/Single%20Service%20Deployment\"}"
